### ISSUE TITLE
RuntimeError: Input type (double) and bias type (float) should be the same

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_mouse-sc_wm-gm_t1#5]
When running 93b47a18f26e1584307b6c8442c1891e1888a1cc, I encountered a `RuntimeError`.

<details><summary>Terminal output</summary>

```console
Path to data: /Users/julien/data.neuro/zurich-mouse
wandb: Currently logged in as: jcohenadad. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.14.0 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.11
wandb: Run data is saved locally in /Users/julien/code/model_seg_mouse-sc_wm-gm_t1/wandb/run-20230315_164533-084ct9i2
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run sweet-pyramid-10
wandb: ⭐️ View project at https://wandb.ai/jcohenadad/mouse-zurich
wandb: 🚀 View run at https://wandb.ai/jcohenadad/mouse-zurich/runs/084ct9i2
----------
epoch 1/100
Backend MacOSX is interactive backend. Turning interactive mode on.
outputs = model(inputs)
PyDev console: starting.
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/Users/julien/code/model_seg_mouse-sc_wm-gm_t1/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/julien/code/model_seg_mouse-sc_wm-gm_t1/venv/lib/python3.10/site-packages/monai/networks/nets/unet.py", line 303, in forward
    x = self.model(x)
  File "/Users/julien/code/model_seg_mouse-sc_wm-gm_t1/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/julien/code/model_seg_mouse-sc_wm-gm_t1/venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/Users/julien/code/model_seg_mouse-sc_wm-gm_t1/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/julien/code/model_seg_mouse-sc_wm-gm_t1/venv/lib/python3.10/site-packages/monai/networks/blocks/convolutions.py", line 316, in forward
    res: torch.Tensor = self.residual(x)  # create the additive residual from x
  File "/Users/julien/code/model_seg_mouse-sc_wm-gm_t1/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/julien/code/model_seg_mouse-sc_wm-gm_t1/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Users/julien/code/model_seg_mouse-sc_wm-gm_t1/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (double) and bias type (float) should be the same
```

</details>

**Comment by jcohenadad** [comment]
Strangely, it says that input is double, but it seems to be float64:
```console
inputs
tensor([[[0.0568, 0.1021, 0.0625,  ..., 0.0796, 0.0676, 0.0294],
         [0.0457, 0.0283, 0.0609,  ..., 0.0377, 0.0631, 0.0407],
         [0.0593, 0.0499, 0.0290,  ..., 0.0712, 0.0675, 0.0346],
         ...,
         [0.0377, 0.0765, 0.0494,  ..., 0.0348, 0.0858, 0.0647],
         [0.0464, 0.0474, 0.0384,  ..., 0.0363, 0.0490, 0.0505],
         [0.0429, 0.0293, 0.0330,  ..., 0.0471, 0.0532, 0.0606]]],
       dtype=torch.float64)
```

**Comment by jcohenadad** [comment]
Adding this transform did not solve the problem:
```python
transforms = Compose(
    [
        EnsureTyped(keys=["image", "label"]),
    ]
)
```

**Comment by jcohenadad** [comment]
What solved it:
```python
transforms = Compose(
    [
        ToTensor(),
    ]
)
```

Source: https://discuss.pytorch.org/t/runtimeerror-input-type-unsigned-char-and-bias-type-float-should-be-the-same/170957

**Comment by jcohenadad** [comment]
Possibly relevant: https://www.kaggle.com/questions-and-answers/256188

> **Note**
> I got the error when setting `device='cpu'` (because I'm doing local debugging)

**Comment by jcohenadad** [comment]
Debugging:
~~~
>>> bias.dtype
torch.float32
>>> input.dtype
torch.float64
~~~

**Comment by jcohenadad** [comment]
This solved it! 🎉
```python
transforms = Compose(
    [
        ToTensor(dtype=np.dtype('float32')),
    ]
)
```

Now getting:
~~~
    raise ValueError("expected 4D input (got {}D input)".format(input.dim()))
ValueError: expected 4D input (got 3D input)
~~~
