### ISSUE TITLE
TypeError: Invalid shape (200,) for image data

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_mouse-sc_wm-gm_t1#7]
Commit: 041e2ff6c2915cf9badc55b58212cb3f71516597

```console
current epoch: 100 current mean dice: 0.0000
best mean dice: 0.0000 at epoch: 10

train completed, best_metric: 0.0000 at epoch: 10
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/p101317/code/model_seg_mouse-sc_wm-gm_t1/train.py", line 300, in <module>
    plt.imshow(torch.argmax(
  File "/home/GRAMES.POLYMTL.CA/p101317/code/model_seg_mouse-sc_wm-gm_t1/venv/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2695, in imshow
    __ret = gca().imshow(
  File "/home/GRAMES.POLYMTL.CA/p101317/code/model_seg_mouse-sc_wm-gm_t1/venv/lib/python3.9/site-packages/matplotlib/__init__.py", line 1442, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/model_seg_mouse-sc_wm-gm_t1/venv/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5665, in imshow
    im.set_data(X)
  File "/home/GRAMES.POLYMTL.CA/p101317/code/model_seg_mouse-sc_wm-gm_t1/venv/lib/python3.9/site-packages/matplotlib/image.py", line 710, in set_data
    raise TypeError("Invalid shape {} for image data"
TypeError: Invalid shape (200,) for image data
```

**Comment by jcohenadad** [comment]
Now fixed
